config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about',as: 'about'
  get "search" => "homes#search",as: 'search'


  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end



  resources :users do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user
    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy

    has_many :favorited_users, through: :favorites, source: :user
    
    def Book.search(search_word)
      Book.where(['category LIKE ?', "#{search_word}"])
    end
    #LIKE句はSQLの検索を行うための演算子
    #category LIKE? = categoryカラムを検索という意味
    

    validates :title, presence: true

    validates :body, presence: true,
                     length: { maximum: 200 }


    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    



end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


        has_many :books, dependent: :destroy
        has_many :book_comments, dependent: :destroy
        has_many :favorites, dependent: :destroy


        has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
        #フォローするユーザー
        has_many :followings, through: :relationships, source: :followed
        #フォローしている人をフォローするユーザーから探す

        has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
        #フォローされるユーザー
        has_many :followers, through: :reverse_of_relationships, source: :follower
        #フォローされてる人をフォローされるユーザーから探す


        attachment :profile_image

        validates :name, presence: true, uniqueness: true,
                         length: { minimum: 2, maximum: 20 }

        validates :introduction, length: { maximum: 50 }



        def follow(user_id)
          relationships.create(followed_id: user_id)
        end
        def unfollow(user_id)
          relationships.find_by(followed_id: user_id).destroy
        end
        def following?(user)
          followings.include?(user)
        end



      def self.search(search,word)
        if search == "forward_match"
          @user = User.where("name LIKE?","#{word}%")
        elsif search == "backward_match"
          @user = User.where("name LIKE?","%#{word}")
        elsif search == "perfect_match"
          @user = User.where("name LIKE?","#{word}")
        elsif search == "partial_match"
          @user = User.where("name LIKE?","%#{word}%")
        else
          @user = User.all
        end


      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top,:about]


  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = BookComment.new(book_comment_params)
    @comment.user = current_user
    @comment.book_id = @book.id
    @comment.save


  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy



  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def create
    @books = Book.all
    @newbook = Book.new(book_params)
    @newbook.user_id = current_user.id
   if @newbook.save
      redirect_to book_path(@newbook.id),notice: "You have created book successfully."
   else
      render :index
   end
  end

  def index
    @newbook = Book.new
    @books = Book.all.order(params[:sort])
    @newbook.user_id = current_user.id

  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path ,notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :category, :rate)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
   before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @favorite = Favorite.new(book_id: @book.id)
    @favorite.user = current_user
    @favorite.save

  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end

def about
end

def search
  @newbook = Book.new
  @books = Book.search(params[:keyword])

  @newbook.user_id = current_user.id
end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  # ——————フォロー機能を作成・保存・削除する————————————

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  #————————フォロー・フォロワー一覧を表示する-————————————

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word]

    if @range == '1'
      @user = User.search(search, word)
    else
      @book = Book.search(search, word)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @newbook = Book.new
    @books =@user.books
  end

  def index
    @users = User.all
    @newbook = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id) ,notice: "You have updated user successfully."
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comments.html.erb
<p>コメント件数：<%= @book.book_comments.count %></p>
  <table>
    <% book.book_comments.each do |book_comment| %>
      <tr>
        <td>
          <%= link_to user_path(book_comment.user) do %>
            <%= attachment_image_tag book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %><br>
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td>
          <%= book_comment.comment %>
        </td>
        <td>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class:"btn btn-sm btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
</table>

app/views/book_comments/create.js.erb
$('#book_comments_<%= @book.id %>').html("<%= j(render "book_comments/book_comments", book: @book) %>");

$('#book_comment_comment').val("")

app/views/book_comments/destroy.js.erb
$('#book_comments_<%= @book.id %>').html("<%= j(render "book_comments/book_comments", book: @book) %>");

app/views/books/_book.html.erb
 <div class="new mt-3">

  <h2>New book</h2>

  <%= form_with model: book, local:true do |f| %>

   <div class="form mb-3">
      <%= f.label :Title %>
      <%= f.text_field :title, class:"form-control" %>
   </div>
   <div class="form mb-3">
      <%= f.label :Opinion %>
      <%= f.text_area :body, class:"form-control" %>
   </div>
   <div class="form mb-3">
      <%= f.label :category %>
      <%= f.text_area :category, class:"form-control" %>
   </div>

   <!-- 評価 -->
   <div class="form-group row" id="star">
     <%= f.label :rate,'評価 ', class:'col-md-3 col-form-label' %>
     <%= f.hidden_field :rate, id: :review_star %>
   </div>

  <!-- 評価javascript -->
   <script>
    $('#star').raty({
     size     : 20,
     starOff:  '<%= asset_path('star-off.png') %>',
     starOn : '<%= asset_path('star-on.png') %>',
     starHalf: '<%= asset_path('star-half.png') %>',
     scoreName: 'book[rate]',
     half: true,
    });
   </script>

   <!-- 'book[rate]'→bookカラムに保存するので忘れないように -->
   <!-- half: true, # ★の半分の入力を行う-->

    <div class="actions mb-3">
      <%= f.submit 'Create Book', class:"btn btn-sm btn-success" %>
    </div>

  <% end %>



</div>

app/views/books/_errors.html.erb
<% if model.errors.any? %>
 <div class="errors">
  <h3>
    <%= model.errors.count %>errors prohibited this obj from being saved:
  </h3>
      <% model.errors.full_messages.each do |message| %>
        <ul>
          <li>
           <%= message %>
          </li>
        </ul>
      <% end %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <%= render 'books/errors', model: @book %>
  <div class="row">
    <div class="col-md-5 mx-auto mt-3">

      <h2>Editing Book</h2>

      <%= form_with model:@book, local:true do |f| %>

        <div class="form mb-3">
          <%= f.label :Title %>
          <%= f.text_field :title, class:"form-control" %>
        </div>

         <div class="form mb-3">
           <%= f.label :Opinion %>
           <%= f.text_field :body, class:"form-control" %>
         </div>

          <!--星評価-->
          <!--idを動的に出来る-->
          <div id="rate_<%= @book.id %>"></div>
          <script>
            $('#rate_<%= @book.id %>').raty({
              size: 20,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= @book.rate %>,
             });
          </script>
          <!--/星評価-->

          <div class="action md-3 mt-3">
             <%= f.submit "Update Book", class:"btn btn btn-success" %>
          </div>
      <% end %>

        <div class="tag mt-3">

          <%= link_to "Show", book_path(@book.id) %>
           |
          <%= link_to "Back", books_path %>
        </div>


    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container mt-3">
    <%= render 'books/errors', model: @newbook %>

  <div class="row">

    <div class="col-md-3">

       <%= render 'users/user', user: current_user %>
       <%= render 'books/book', book: @newbook %>
    </div>

    <div class="col-md-8 offset-md-1">

        <h2>Books</h2>

      <%= link_to"新しい順", books_path(sort: 'created_at DESC')%>｜<%= link_to"評価の高い順", books_path(sort: 'rate DESC') %>

      <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th>category</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        <tbody>



          <% @books.each do |book| %>

              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>

                <td><%= book.body %></td>

                <td><%= book.category %></td>

                <td>
                   <td id="favorite-btn_<%= book.id %>">
                  <%= render "favorites/favorite-btn", book: book %>
                </td>

                <td>コメント数:<%= book.book_comments.count %></td>

                <!--星評価-->
               <td>
                 <!--idを動的に出来る-->
                <div id="rate_<%= book.id %>"></div>
                <script>
                  $('#rate_<%= book.id %>').raty({
                    size: 20,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: <%= book.rate %>,
                  });
                </script>
               </td>

                <!--/星評価-->

              </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container mt-3">
  <%= render 'books/errors', model: @newbook %>

    <div class="row">


      <div class="col-md-3 mt-3">

        <%= render 'users/user', user: @user %>
        <%= render 'books/book', book: @newbook %>
      </div>

        <div class="col-md-8 offset-md-1 mt-3">

          <h2>Book detail</h2>

            <table class='table'>
             <tr>

               <td>
                 <%= link_to user_path(@book.user) do %>
                    <%= attachment_image_tag @book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %><br>
                    <%= @book.user.name %>
                 <% end %>
               </td>
               <td>
                 <%= @book.title %>
               </td>
               <td>
                 <%= @book.body %>
               </td>
               <td>
                 <%= @book.category %>
               </td>

               <td id="favorite-btn_<%= @book.id %>">
                 <%= render "favorites/favorite-btn", book: @book %>
               </td>

               <!--星評価-->
               <td>
                <div id="rate_<%= @book.id %>"></div>
                <script>
                  $('#rate_<%= @book.id %>').raty({
                    size: 20,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: <%= @book.rate %>,
                  });
                </script>
               </td>


                <!--/星評価-->



                <% if @book.user == current_user %>

                   <td>
                     <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %>
                   </td>
                   <td>
                     <%= link_to "Destroy", book_path(@book), method: :delete, data:{confirm: "本当に消しますか？"}, class:"btn btn-sm btn-danger" %>
                   </td>

                <% end %>
               </tr>
            </table>

              <div id="book_comments_<%= @book.id %>">
                <%= render "book_comments/book_comments", book: @book  %>
              </div>


            <%= form_with(model:[@book,@book_comment],remote: true) do |f| %>
                <%= f.text_area :comment, rows:'5', class:"form-control" %>
                <%= f.submit "送信", class:"mt-3" %>
            <% end %>

        </div>

   </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
       ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
       ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite-btn_<%= @book.id %>').html("<%= j(render "favorites/favorite-btn", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite-btn_<%= @book.id %>').html("<%= j(render "favorites/favorite-btn", book: @book) %>");

app/views/homes/about.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col=11 mx-auto">

      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>

    </div>

  </div>

</div>

app/views/homes/search.html.erb
<div class="container mt-3">
    <%= render 'books/errors', model: @newbook %>

  <div class="row">

    <div class="col-md-3">

       <%= render 'users/user', user: current_user %>
       <%= render 'books/book', book: @newbook %>
    </div>

    <div class="col-md-8 offset-md-1">

        <h2>Books</h2>

      <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th>category</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        <tbody>



          <% @books.each do |book| %>

              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>

                <td><%= book.body %></td>

                <td><%= book.category %></td>

                <td>
                   <td id="favorite-btn_<%= book.id %>">
                  <%= render "favorites/favorite-btn", book: book %>
                </td>

                <td>コメント数:<%= book.book_comments.count %></td>

                <!--星評価-->
               <td>
                 <!--idを動的に出来る-->
                <div id="rate_<%= book.id %>"></div>
                <script>
                  $('#rate_<%= book.id %>').raty({
                    size: 20,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: <%= book.rate %>,
                  });
                </script>
               </td>

                <!--/星評価-->

              </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container mt-3" >
 <div class="row">
   <div class = "col=11 mx-auto">

      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers !!</strong></h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></p>

        <p>you can share and exchange your opinions , inpressions , and emotions</p>

        <p>about various books!</p>

     <div class = "btn-wrapper col-10 mx-auto">
       <div class = "row">
         <%= link_to "Log in",new_user_session_path,class: "btn btn-info btn-sm btn-block mb-3 sing in" %>
         <%= link_to "Sign up",new_user_registration_path,class: "btn btn-success btn-sm btn-block mb-3 sing up" %>
       </div>
     </div>


   </div>
 </div>
</div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
 <table class="table">
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
 </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
 <table class="table">
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
 </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searches/search.html.erb
<!--books一覧 -->

<% if @range == '2' %>
<h2>Books search for "<%= params[:word] %>"</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
     <% @book.each do |book| %>
     <tr>
      <td>
       <%= link_to(book.user) do %>
       <%= attachment_image_tag book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "50x50" %>
       <% end %>
      </td>
      <td>
       <%= link_to book.title, book, class: "book_#{book.id}" %>
      </td>
      <td><%= book.body %></td>
     </tr>
     <% end %>
  </tbody>
</table>

<% else %>
<h2>Users search for "<%= params[:word] %>"</h2>
<table class="table table-hover table-inverse">
  <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
    <% @user.each do |user| %>
     <tr>
      <td><%= attachment_image_tag user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "50x50" %></td>
      <td><%= user.name%></td>
      <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
     </tr>
    <% end %>
   </tbody>
</table>
<% end %>

app/views/users/_user.html.erb
<h2>User info</h2>

  <%= attachment_image_tag user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %>
  <table class="table">
    <tbody>
       <tr>
         <th>name</th>
         <th><%= user.name %></th>
       </tr>
         <th>introduction</th>
         <th><%= user.introduction %></th>
       </tr>
       <tr>
         <th>follows</th>
         <th>
           <%= link_to user_followings_path(user) do %>
             <%= user.followings.count %>
           <% end %>
         </th>
       </tr>
       <tr>
         <th>followers</th>
         <th>
           <%= link_to user_followers_path(user) do%>
             <%= user.followers.count %>
           <% end %>
         </th>
       </tr>
    </tbody>
  </table>

    <td>
     <% if current_user != user %>

       <% if current_user.following?(user) %>
         <%= link_to "フォロー外す", user_relationship_path(user_id: user, id: user), method: :delete, class:"btn btn-sm btn-info" %>
       <% else %>
         <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-sm btn-success" %>
       <% end %>

     <% end %>
    </td>


      <% if current_user == user %>
        <div class="row">
          <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
      　    <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
      <% end %>

app/views/users/edit.html.erb
<div class="container ">
  <div class="row">

    <div class="col-md-5 mx-auto mt-3">

       <h2>User info</h2>

       <%= render 'books/errors', model: @user %>

      <%= form_with model:@user, local:true do |f| %>

       <div class="form-group mb-3">
            <%= f.label :Name %>
            <%= f.text_field :name, class:"form-control" %>
       </div>

          <div class="form-groupe mb-3">
             <%= f.label :Image %>
             <%= f.attachment_field :profile_image, placeholder: "プロフィール画像",class:"form-control-file" %>
          </div>

            <div class="form-group mb-3">
              <%= f.label :Introduction %>
              <%= f.text_field :introduction, class:"form-control" %>
            </div>

               <div class="actions mb-3">
                  <%= f.submit "Update User", class:"btn btn btn-secondary" %>
               </div>


      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-3">
  <%= render 'books/errors', model: @newbook %>
  <div class="row">

    <div class="col-md-3">
      <%= render 'users/user', user: current_user %>

      <%= render 'books/book', book: @newbook %>
    </div>

      <div class="col-md-8 offset-md-1">

        <h2>Users</h2>

        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>image</th>

              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>

              <tbody>

                <% @users.each do |user| %>
                 <tr>

                   <td><%= attachment_image_tag user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %></td>

                   <td><%= user.name %></td>
                   <td>フォロー数:<%= user.followings.count %></td>
                   <td>フォロワー数:<%= user.followers.count %></td>

                    <td>
                     <% if current_user != user %>

                       <% if current_user.following?(user) %>
                         <%= link_to "フォロー外す", user_relationship_path(user_id: user, id: user), method: :delete %>
                       <% else %>
                         <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                       <% end %>

                     <% end %>
                    </td>

                   <td><%= link_to "Show",user_path(user) %></td>

                 </tr>
                <% end %>
              </tbody>
          </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3">
  <%= render 'books/errors', model: @newbook %>
 <div class="row">

  <div class="col-md-3">
    <%= render 'users/user', user: @user %>
     <%= render 'books/book', book: @newbook %>

  </div>

   <div class="col-md-8 offset-md-1">

     <h2>Books</h2>

      <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th>category</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        <tbody>

         <% @books.each do |book| %>

            <tr>
              <%= link_to user_path(@user) do %>
                <td>
                  <%= attachment_image_tag @user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                  <% end %>
                <td><%= book.body %></td>
                <td><%= book.category %></td>
                <td>
                 コメント件数：<%= book.book_comments.count %>
                </td>
                  <!--星評価-->
               <td>
                 <!--idを動的に出来る-->
                <div id="rate_<%= book.id %>"></div>
                <script>
                  $('#rate_<%= book.id %>').raty({
                    size: 20,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: <%= book.rate %>,
                  });
                </script>
               </td>

                <!--/星評価-->

              <% end %>
            </tr>
        </tbody>
      </table>

   </div>
 </div>
</div>