config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about',as: 'about'
  get "search" => "homes#search",as: 'search'


  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end



  resources :users do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user
    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy

    has_many :favorited_users, through: :favorites, source: :user
    
    def Book.search(search_word)
      Book.where(['category LIKE ?', "#{search_word}"])
    end
    #LIKE句はSQLの検索を行うための演算子
    #category LIKE? = categoryカラムを検索という意味
    

    validates :title, presence: true

    validates :body, presence: true,
                     length: { maximum: 200 }


    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    



end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


        has_many :books, dependent: :destroy
        has_many :book_comments, dependent: :destroy
        has_many :favorites, dependent: :destroy


        has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
        #フォローするユーザー
        has_many :followings, through: :relationships, source: :followed
        #フォローしている人をフォローするユーザーから探す

        has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
        #フォローされるユーザー
        has_many :followers, through: :reverse_of_relationships, source: :follower
        #フォローされてる人をフォローされるユーザーから探す


        attachment :profile_image

        validates :name, presence: true, uniqueness: true,
                         length: { minimum: 2, maximum: 20 }

        validates :introduction, length: { maximum: 50 }



        def follow(user_id)
          relationships.create(followed_id: user_id)
        end
        def unfollow(user_id)
          relationships.find_by(followed_id: user_id).destroy
        end
        def following?(user)
          followings.include?(user)
        end



      def self.search(search,word)
        if search == "forward_match"
          @user = User.where("name LIKE?","#{word}%")
        elsif search == "backward_match"
          @user = User.where("name LIKE?","%#{word}")
        elsif search == "perfect_match"
          @user = User.where("name LIKE?","#{word}")
        elsif search == "partial_match"
          @user = User.where("name LIKE?","%#{word}%")
        else
          @user = User.all
        end


      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top,:about]


  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def create
    @books = Book.all
    @newbook = Book.new(book_params)
    @newbook.user_id = current_user.id
   if @newbook.save
      redirect_to book_path(@newbook.id),notice: "You have created book successfully."
   else
      render :index
   end
  end

  def index
    @newbook = Book.new
    @books = Book.all.order(params[:sort])
    @newbook.user_id = current_user.id

  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path ,notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :category, :rate)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
   before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @favorite = Favorite.new(book_id: @book.id)
    @favorite.user = current_user
    @favorite.save

  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end

def about
end

def search
  @newbook = Book.new
  @books = Book.search(params[:keyword])

  @newbook.user_id = current_user.id
end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word]

    if @range == '1'
      @user = User.search(search, word)
    else
      @book = Book.search(search, word)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @newbook = Book.new
    @books =@user.books
  end

  def index
    @users = User.all
    @newbook = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id) ,notice: "You have updated user successfully."
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
         <a class="navbar-brand" href="/"><span>Bookers</span></a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse" id="navbarNavDropdown">

       <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>

         <li>
            <%= link_to user_path(current_user) do %>
              <i class="fas fa-home nav-link text-light"> Home</i>
            <% end %>
         </li>
         <li>
           <%= link_to users_path do %>
              <i class="fas fa-users nav-link text-light"> Users</i>
           <% end %>
         </li>
         <li>
           <%= link_to books_path do %>
              <i class="fas fa-book-open nav-link text-light"> Books</i>
           <% end %>
         </li>
         <li>
           <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt nav-link text-light"> logout</i>
           <% end %>
         </li>
        <% else %>
         <li>
           <%= link_to root_path do %>
              <i class="fas fa-home nav-link text-light"> Home</i>
           <% end %>
         </li>
         <li>
           <%= link_to about_path do %>
              <i class="fas fa-link nav-link text-light"> About</i>
           <% end %>
         </li>
         <li>
           <%= link_to new_user_registration_path do %>
              <i class="fas fa-user-plus nav-link text-light"> sign up</i>
           <% end %>
         </li>
         <li>
           <%= link_to new_user_session_path do %>
              <i class="fas fa-sign-in-alt nav-link text-light"> login</i>
           <% end %>
         </li>

        </ul>

        <% end %>

        <%= form_with url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword %>
            <%= f.submit '検索', class: 'btn btn-primary'  %>
        <% end %>
      </div>
    </div>
  </header>


  　<% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>




    <%= yield %>


    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class ="mx-auto">CopyRight Infratop.inc</div>
        </div>
      </div>
    </footer>
  </body>
</html>